### ISSUE TITLE
Get a lot of compiler error

### ISSUE THREAD

**Issue by j4nos** [stklieme/HTMLDocument#4]
I get a lot of unresolved identifier error i.e.: xmlNodePtr, xmlXPathNewContext
![screen shot 2015-06-13 at 22 49 44](https://cloud.githubusercontent.com/assets/11924475/8145953/8a614e40-121e-11e5-99f8-8af1380a66d7.png)

**Comment by stklieme** [comment]
Hi,

did you add libxml2 properly?

Regards

Stefan

**Comment by j4nos** [comment]
Yes, as you specified in the manual, but at the end I found an other solution
